### ISSUE TITLE
pip install hexpy failing

### ISSUE THREAD

**Issue by TrueInsight** [sullivancolin/hexpy#14]
I tried pip install hexpy, but received an error:
  ModuleNotFoundError: No module named 'setuptools'
See the attached file for the complete output.
[hexpy install fail.txt](https://github.com/sullivancolin/hexpy/files/4412703/hexpy.install.fail.txt)

**Comment by sullivancolin** [comment]
Pendulum is a dependency library of this project, which seems to be missing the right wheel for your windows distribution of Python in it's latest release.  Issue referenced here: https://github.com/sdispater/pendulum/issues/456

Failing to find a matching wheel `pip` attempts to build the pendulum package itself, but the build seems to be failing.  This issue is referenced here: https://github.com/sdispater/pendulum/issues/454

try `pip install pendulum==2.0.5` to downgrade pendulum, followed by `pip install hexpy`

**Comment by TrueInsight** [comment]
Brilliant! That worked. Looking forward to trying out hexpy.
